In [1]:
import numpy as np

In [573]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def loglos(y, y_pred):
    loss = np.zeros(y.shape)
    loss[y == 0] = -(1.0 - y[y == 0]) * np.log(1.0 - y_pred[y == 0] + 1e-14)
    loss[y == 1] = -y[y == 1] * np.log(y_pred[y == 1] + 1e-14)
    return np.sum(loss)


In [666]:
class LogisticRegression():
    def __init__(self, iterations=1e+4, alpha=1e-4, eps=1e-8, l1_alpha=0, l2_alpha=0, random_state=False):
        self.iterations = iterations
        self.alpha = alpha
        self.eps = eps
        self.l1_alpha = l1_alpha
        self.l2_alpha = l2_alpha
        self.random_state = random_state
    
    def fit(self, X, y):
        if self.random_state:
            np.random.seed(self.random_state)
        W = np.zeros(X.shape[0])
        n = X.shape[1]
        loss_prev, loss_diff, i = 0, np.inf, 1
        while loss_diff > self.eps and i < self.iterations:
            y_pred = sigmoid(np.dot(W, X))
            loss = loglos(y, y_pred)
            loss_diff , loss_prev = abs(loss_prev - loss), loss
            
            l1_term = self.l1_alpha * np.sign(W) if self.l1_alpha else 0
            l2_term = self.l2_alpha * W if self.l2_alpha else 0 
            
            W -= (self.alpha * (1/n * np.sum(X * (y_pred - y), axis=1)) + l1_term + l2_term)
            i += 1
            if i % (self.iterations / 10) == 0:
                print(i, y_pred, '\n', loss)
        self.__W = W.copy()
    
    def predict(self, X):
        return (self.predict_proba(X) > 0.5).astype('int8')
    
    def predict_proba(self, X):
        return (sigmoid(self.__W.T @ X)) 
    
    @property
    def weights(self):
        return self.__W

In [625]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2],
              [500, 700, 750, 600, 1450,
               800, 1500, 2000, 450, 1000],
              [1, 1, 2, 1, 2, 
               1, 3, 3, 1, 2]], dtype = np.float64)
y = np.array([0, 0, 1, 0, 1,
              0, 1, 0, 1, 1], dtype = np.float64)

In [661]:
model = LogisticRegression(iterations=1e+7, alpha=5e-5)

In [662]:
model.fit(X, y)

1000000 [9.16340686e-02 3.33270565e-02 2.35811134e-01 5.56892898e-02
 6.72832781e-04 1.77333374e-01 5.63134907e-04 2.74926994e-10
 1.16558420e-01 7.46168271e-02] 
 21.35798832874148
2000000 [3.36728474e-02 6.29693377e-03 3.48738184e-01 1.46422565e-02
 1.29426886e-05 2.22828393e-01 1.03079985e-05 1.08107910e-17
 5.06581225e-02 5.97882195e-02] 
 29.898020363256958
3000000 [1.33356457e-02 1.04270084e-03 7.16862980e-01 3.74197204e-03
 2.07253772e-06 4.33868444e-02 3.21507611e-05 5.70166370e-19
 2.49981574e-02 9.34426251e-02] 
 29.886616356959834
4000000 [8.21494686e-03 4.11709674e-04 9.55934659e-01 1.84364429e-03
 3.68210034e-06 1.46197009e-02 1.19912358e-03 6.01831735e-18
 1.72381170e-02 3.37485361e-01] 
 24.45535629778012
5000000 [2.42227175e-03 6.58896829e-05 9.82246440e-01 3.99841063e-04
 1.18771609e-06 1.66197762e-03 6.46056769e-03 9.29881315e-18
 5.94693523e-03 3.78647700e-01] 
 24.804012190854127
6000000 [2.38826544e-04 1.77587108e-06 9.49099789e-01 2.05963527e-05
 1.04616665e-08 9.

In [663]:
model.weights

array([-1.44706650e+01, -3.22061797e+00, -1.41044274e-02,  2.37322420e+01])

In [664]:
model.predict_proba(X) 

array([0.26673438, 0.02120386, 0.99999988, 0.08153305, 0.94687631,
       0.11691597, 1.        , 0.02438801, 0.42408326, 0.99999608])

In [669]:
model.predict_proba(X)

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1])