In [1]:
import numpy as np

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [2]:
A = np.array([
    [1, 2, 0],
    [0, 0, 5],
    [3,-4, 2],
    [1, 6, 5],
    [0, 1, 0]
])

In [19]:
U, d, VT = np.linalg.svd(A)
V = VT.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(len(d))] = d
print('U matrix \n', U)
print('D matrix \n', D)
print('V matrix \n', V)

U matrix 
 [[ 0.17056501  0.15680918 -0.53077508 -0.79905375 -0.16158397]
 [ 0.39287016 -0.52933945  0.6134793  -0.43375771  0.03082495]
 [-0.14366152 -0.82449256 -0.52379105  0.14049848  0.07400343]
 [ 0.88843702  0.06074346 -0.24655277  0.37755832 -0.06042632]
 [ 0.08125046  0.10831843 -0.08231425 -0.10524851  0.98173958]]
D matrix 
 [[8.82486885 0.         0.        ]
 [0.         6.14060608 0.        ]
 [0.         0.         2.53271528]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
V matrix 
 [[ 0.07116451 -0.36737824 -0.92734505]
 [ 0.71702467  0.66514082 -0.20847855]
 [ 0.69340553 -0.65009301  0.31075368]]


In [16]:
print(np.dot(np.dot(U, D), V.T))

[[ 1.00000000e+00  2.00000000e+00  1.31018987e-15]
 [ 1.93009612e-16 -2.66609409e-15  5.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00  2.00000000e+00]
 [ 1.00000000e+00  6.00000000e+00  5.00000000e+00]
 [-5.49534701e-17  1.00000000e+00 -3.02821608e-17]]


2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [30]:
print('Евклидова норма А = ', np.linalg.norm(A, 2))
print('или')
print('На основании сингулярного разложения А норма  = ', d[0])

Евклидова норма А =  8.824868854820444
или
На основании сингулярного разложения А норма  =  8.824868854820444


In [33]:
print('Фробениуса норма А = ', np.linalg.norm(A))
print('или')
print('На основании сингулярного разложения А норма  = ', np.dot(d, d)**0.5)

Фробениуса норма А =  11.045361017187261
или
На основании сингулярного разложения А норма  =  11.045361017187263
