In [1]:
import numpy as np

In [2]:
a = np.array([l for l in range(12, 24)])
a


array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [3]:
a1 = np.reshape(a, (2, 6))
a2 = np.reshape(a, (3, 4))
a3 = np.reshape(a, (4, 3))
a4 = np.reshape(a, (6, 2))
a5 = np.reshape(a, (12, 1))

In [4]:
b1 = np.reshape(a, (-1, 6))
b2 = np.reshape(a, (-1, 4))
b3 = np.reshape(a, (-1, 3))
b4 = np.reshape(a, (6, -1))
b5 = np.reshape(a, (12, -1))

In [5]:
mu, sigma = 0, 1
normal = np.random.normal(mu, sigma, (3, 4))
normal


array([[-1.13992973,  0.85547942,  0.04392366,  0.25409964],
       [ 1.34968462,  1.11279797, -1.0028378 , -0.00543453],
       [ 1.4264004 ,  0.59952326,  0.23884147, -1.08639356]])

In [6]:
a = [i for i in range(20, 0, -2)]
a


[20, 18, 16, 14, 12, 10, 8, 6, 4, 2]

In [7]:
b = [a.copy()]
b


[[20, 18, 16, 14, 12, 10, 8, 6, 4, 2]]

In [8]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
c = np.vstack((a, b))
c.size


10

In [9]:
a = np.array([i for i in range(12)])
A = a.reshape(4, 3)
At = A
At = At.T
B = np.dot(A, At)
print(B.shape)
B


(4, 4)


array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [10]:
np.linalg.det(B)
# Определитель 0

0.0

In [11]:
np.random.seed(42)

In [12]:
c = np.random.randint(16, size=16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [13]:
C = np.reshape(c, (4, 4))

In [14]:
C = C * 10
C

array([[ 60,  30, 120, 140],
       [100,  70, 120,  40],
       [ 60,  90,  20,  60],
       [100, 100,  70,  40]])

In [15]:
D = C + B
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [16]:
det = np.linalg.det(D)
rank = np.linalg.matrix_rank(D)
print(f'Ранк матрицы D: {rank}. Определитель: {det}')

Ранк матрицы D: 4. Определитель: -28511999.999999944


In [17]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

In [18]:
D_inv = np.where(D_inv > 0, D_inv, 0)
D_inv = np.where(D_inv <= 0, D_inv, 1)
D_inv.astype('int32')

array([[1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]], dtype=int32)

In [19]:
E = np.where(D_inv == 1, B, C)
E

array([[  5,  14,  23, 140],
       [100,  70, 120, 122],
       [ 60,  90,  20, 212],
       [ 32, 100, 212,  40]])