In [1]:
import numpy as np

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

In [52]:
A = np.array([
    [-1, -6],
    [ 2,  6]
])
w, v = np.linalg.eig(A)
print(f'Собсвенные числа для А \n{w}')
print(f'Собсвенные вектора для А \n{v}')

Собсвенные числа для А 
[2. 3.]
Собсвенные вектора для А 
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


Проверим вектора из решения на листочке
для <br>
$\lambda_{1} = 2$ $x_{1} = (-2, 1)$ <br>
$\lambda_{2} = 3$ $x_{2} = (-3, 2)$ <br>

In [53]:
l1 = 2
x1 = np.array([-2, 1])
l2 = 3
x2 = np.array([-3, 2])

In [55]:
list(A.dot(x1)) == list(l1 * x1)

True

In [56]:
list(A.dot(x2)) == list(l2 * x2)

True

__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

In [57]:
A = np.array([
    [-1, 0],
    [ 0, -1]
])
w, v = np.linalg.eig(A)
print(f'Собсвенные числа для А \n{w}')
print(f'Собсвенные вектора для А \n{v}')

Собсвенные числа для А 
[-1. -1.]
Собсвенные вектора для А 
[[1. 0.]
 [0. 1.]]


Доказательство на листочке

__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

In [58]:
A = np.array([
    [ 1, 1],
    [-1, 3]
])
x = np.array([1, 1])
w, v = np.linalg.eig(A)
print(f'Собсвенные числа для А \n{w}')

Собсвенные числа для А 
[2.00000002 1.99999998]


In [60]:
l = 2
list(A.dot(x)) == list(2 * x)

True

__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.ь

In [61]:
A = np.array([
    [0, 3, 0],
    [3, 0, 0],
    [0, 0, 3],
])
x = np.array([3, -3, -4])
w, v = np.linalg.eig(A)
print(f'Собсвенные числа для А \n{w}')

Собсвенные числа для А 
[ 3. -3.  3.]


In [66]:
for w_ in w:
    print(list(int(w_) * x))
    print(list(A.dot(x)))
    print(list(A.dot(x)) == list(w_ * x))

[6, -6, -8]
[-9, 9, -12]
False
[-9, 9, 12]
[-9, 9, -12]
False
[9, -9, -12]
[-9, 9, -12]
False
